import type { Metadata } from "next";
import { Inter, Raleway, Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <main className="flex min-h-screen w-full flex-col items-center gap-4 bg-bg p-4 pb-16">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
